# general
gpu_id: 0
use_gpu: True
seed: 2020
state: INFO
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved'
show_progress: True
save_dataset: False
save_dataloaders: False

# training settings
epochs: 40
train_batch_size: 256
learner: adam
learning_rate: 0.001
neg_sampling:
  uniform: 1
eval_step: 1
stopping_step: 10
clip_grad_norm: ~
# clip_grad_norm:  {'max_norm': 5, 'norm_type': 2}
weight_decay: 0.0001
require_pow: False
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"
MAX_ITEM_LIST_LENGTH: 50
MIN_ITEM_LIST_LENGTH: 1
load_col:
    inter: ['user_id', 'item_id', 'rating', 'timestamp', 'item_id_list_field', 'item_length']

# evaluation settings
# #{'LS':[0.8,0.1,0.1]}

eval_args:
  split: {'LS': 'valid_and_test'}
  group_by: user
  order: TO
  mode: full
repeatable: True
metrics: ["Hit","NDCG"]
topk: [5, 10, 20]
valid_metric: NDCG@5
valid_metric_bigger: True
eval_batch_size: 256
loss_decimal_place: 4
metric_decimal_place: 4


n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'CE'
lmd: 0.1
lmd_sem: 0.1
aug: 'self'

n_mixers: 1
seq_inner_size: 256
item_inner_size: 256

temperature: 0.07

filter1_cts: False
filter2_cts: False

hidden_size_factor: 2
segment_num: 5
segment_len: 20
hop_len: 5